# Change these first
owner: LACMTA # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Metro.net
    url: https://metro.net/
  - name: Metro.net Schedules Page
    url: https://metro.net/riding/schedules/
    maxResponseTime: 50000
    __dangerous__body_down_if_text_missing: 'Azusa - Long Beach'
  - name: Metro API
    url: https://api.metro.net
    maxResponseTime: 50000
    method: GET
    headers:
      - "Content-Type: application/json"
  - name: Metro Timetables API root
    url: https://timetables.metroservices.io/api/v1
    maxResponseTime: 50000
  - name: Prod Timetables API - Bus Routes
    url: https://timetables.metroservices.io/api/v1/agencies/LACMTA/routes/
    __dangerous__body_down_if_text_missing: '"agency_id": "LACMTA"'
    maxResponseTime: 50000
  - name: Prod Timetables API - Rail Routes
    url: https://timetables.metroservices.io/api/v1/agencies/LACMTA_Rail/routes/
    __dangerous__body_down_if_text_missing: '"agency_id": "LACMTA_Rail"'
    maxResponseTime: 50000
  - name: Staging Timetables API - Rail Routes
    url: https://stage-timetables-api.metroservices.io/api/v1/agencies/LACMTA/routes/
    __dangerous__body_down_if_text_missing: '"agency_id": "LACMTA"'
    maxResponseTime: 50000
  - name: Staging Timetables API - Bus Routes
    url: https://stage-timetables-api.metroservices.io/api/v1/agencies/LACMTA_Rail/routes/
    __dangerous__body_down_if_text_missing: '"agency_id": "LACMTA_Rail"'
    maxResponseTime: 50000
  - name: Swiftly API
    url: https://transitime-api.goswift.ly/api/v1/key/81YENWXv/agency/lametro/command/agency
  - name: Swiftly Bus Arrivals Map
    url: https://live.goswift.ly/lametro/
  - name: Swiftly Rail Arrivals Map
    url: https://live.goswift.ly/lametro-rail/


workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://github.com/LACMTA/marketing-docs/raw/dev/site/assets/metro_logo.png
  name: Metro web services uptime 
  introTitle: "Monitoring of Metro web services"
  introMessage: This website monitors up time for Metro related services. It uses an open source tool called Upptime.
  navbar:
    - title: Status
      href: /uptime
    - title: GitHub
      href: https://github.com/LACMTA/uptime
  links:
    - rel: stylesheet
      href: https://lacmta.github.io/design-system/dist/css/styles.css

assignees:
  - matikin9
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
