# Change these first
owner: LACMTA # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Metro.net
    url: https://metro.net/
  - name: Swiftly API
    url: https://transitime-api.goswift.ly/api/v1/key/81YENWXv/agency/lametro/command/agency
  - name: Metro API v2
    url: https://api.metro.net/time

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://github.com/LACMTA/marketing-docs/raw/dev/site/assets/metro_logo.png
  name: Metro web services uptime 
  introTitle: "Monitoring of Metro web services"
  introMessage: This website monitors up time for Metro related services. It uses an open source tool called Upptime.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  # links:
  #   - rel: stylesheet
  #     href: https://lacmta.github.io/design-system/dist/css/styles.css

assignees:
  - matikin9
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
